services:
  compass-voice:
    image: arushahmd/compass-voice:latest
    container_name: compass-voice
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: compass-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  cli:
    image: arushahmd/compass-voice:latest
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: python app/cli/main.py
